[package]
name = "filterlab_ref"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "read"
harness = false

[[bench]]
name = "read_write"
harness = false
